name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B clean package

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: "/opt/tomcat/webapps/*.war"
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    - uses: actions/checkout@master
    - run: |
           mvn -B clean package
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "BoschcregutCharles.war"
        target: "/opt/tomcat/webapps"
